env:
  browser: true
  es2022: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - prettier
plugins:
  - "@typescript-eslint"
  - import
rules:
  import/no-unresolved: error
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node:
      extensions:
        - ".js"
        - ".ts"
